### ISSUE TITLE
Show redundant whitelist entries

### ISSUE THREAD

**Issue by DanaKirsh** [mainmatter/ember-intl-analyzer#645]
List entries in the whitelist that are not needed anymore

**Comment by Mikek2252** [comment]
Thanks @robinborst95 for adding this feature, It is now available in ember 4.6.0

**Comment by robinborst95** [comment]
Thanks for the release! I've just tried it in our application, and at first it showed entries that weren't supposed to be redundant, so I thought I missed something. However, it turns out that there was 1 whitelist entry that whitelisted way more translations than intended, one along the lines of `prefix\.(a|b)_count|onboarding` that made all translations containing `onboarding` whitelisted, where it was supposed to be `prefix\.((a|b)_count|onboarding)`. Fixing this entry found a whole bunch of unused translations keys that contained `onboarding`, so I could remove all of those now :broom:! So, for us it has already proven to be useful :raised_hands:

**Comment by DanaKirsh** [comment]
Would it be possible to extend this to show when a regex is not redundant but is not as specific as possible? for example, we had `foo\.(bar|baz)` with both `foo.bar` and `foo.baz` used in the app. I removed `foo.baz` from the app/translation file but intl-analyzer didn't point it out as the whitelist entry was still matched `foo.bar`
